version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
  
  school-api:
    build:
        context: ../school-api
    environment:
        MONGODB_URI: 'mongo:27017'
    ports:
    - "3000:3000"
  class-api:
    build:
      context: ../class-api
    environment:
      MONGODB_URI: 'mongo:27017'
    ports:
    - "3001:3000"
  subject-api:
    build:
      context: ../subject-api
    environment:
      MONGODB_URI: 'mongo:27017'
    ports:
    - "3002:3000"
  